### PR TITLE
Make MTU optional for VRFrouteconfiguration

### PR DESCRIPTION
**Pull request by watzkuh**

### CODE REVIEW

**Comment by schrej** [comment]
Is this safe to just omit?

Took a brief look at the code, and at least in one location defaulting doesn't seem to be properly implemented: https://github.com/telekom/das-schiff-network-operator/blob/main/pkg/nl/layer3.go#L191

**Comment by watzkuh** [comment]
I'm not entirely sure. I'm only assuming it because from what I can see we have the value is only set for 3 of our own VRFRouteConfigurations and unset for 816 of them* and I was hoping they weren't all broken.

(*assuming I greped correctly)

**Comment by chdxD1** [comment]
@schrej good catch, that line should also contain `info.linkMTU()` however it had no impact so far

**Comment by chdxD1** [comment]
@watzkuh If you could change the line mentioned by Jakob from `info.MTU` to `info.linkMTU` I approve this PR

**Comment by watzkuh** [comment]
@chdxD1 Done!

**Review by chdxD1 — APPROVED** [review]
lgtm

**Pull request merged**
